#
# Copyright (C) 2016 Jakub Skopal <j@kubs.cz>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for cntlm
LUCI_DEPENDS:=+cntlm

include ../luci.mk

# call BuildPackage - OpenWrt buildroot signature
